PUT http://localhost:3001/api/blogs/678b99102746904a8910ebcf?
Content-Type: application/json

{
    "title": "Test Blog",
    "author": "Firstname Lastname",
    "url": "Google.com",
    "likes": 71,
    "comments": ["very informative!", "SO FUNNY!!!!"]
}